export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAILED = "LOGIN_API_FAILED";

export const REGISTER_API = "REGISTER_API";
export const REGISTER_API_SUCCEED = "REGISTER_API_SUCCEED";
export const REGISTER_API_FAILED = "REGISTER_API_FAILED";

export const ADMIN_GET_LIST_MOD = "ADMIN_GET_LIST_MOD";
export const ADMIN_GET_LIST_MOD_SUCCEED = "ADMIN_GET_LIST_MOD_SUCCEED";
export const ADMIN_GET_LIST_MOD_FAILED = "ADMIN_GET_LIST_MOD_FAILED";

export const ADMIN_GET_LIST_COMPANY = "ADMIN_GET_LIST_COMPANY";
export const ADMIN_GET_LIST_COMPANY_SUCCEED = "ADMIN_GET_LIST_COMPANY_SUCCEED";
export const ADMIN_GET_LIST_COMPANY_FAILED = "ADMIN_GET_LIST_COMPANY_FAILED";

export const ADMIN_GET_LIST_ITER = "ADMIN_GET_LIST_ITER";
export const ADMIN_GET_LIST_ITER_SUCCEED = "ADMIN_GET_LIST_ITER_SUCCEED";
export const ADMIN_GET_LIST_ITER_FAILED = "ADMIN_GET_LIST_ITER_FAILED";

export const ADD_MOD_API = "ADD_MOD_API";
export const ADD_MOD_API_SUCCEED = "ADD_MOD_API_SUCCEED";
export const ADD_MOD_API_FAILED = "ADD_MOD_API_FAILED";

export const DELETE_MOD_API = "DELETE_MOD_API";
export const DELETE_MOD_API_SUCCEED = "DELETE_MOD_API_SUCCEED";
export const DELETE_MOD_API_FAILED = "DELETE_MOD_API_FAILED";

export const DELETE_COMPANY_API = "DELETE_COMPANY_API";
export const DELETE_COMPANY_API_SUCCEED = "DELETE_COMPANY_API_SUCCEED";
export const DELETE_COMPANY_API_FAILED = "DELETE_COMPANY_API_FAILED";

export const DELETE_ITER_API = "DELETE_ITER_API";
export const DELETE_ITER_API_SUCCEED = "DELETE_ITER_API_SUCCEED";
export const DELETE_ITER_API_FAILED = "DELETE_ITER_API_FAILED";

export const ADMIN_GET_USER_PERMISSIONS = "ADMIN_GET_USER_PERMISSIONS";
export const ADMIN_GET_USER_PERMISSIONS_SUCCEED =
  "ADMIN_GET_USER_PERMISSIONS_SUCCEED";
export const ADMIN_GET_USER_PERMISSIONS_FAILED =
  "ADMIN_GET_USER_PERMISSIONS_FAILED";

export const ADMIN_UPDATE_USER_PERMISSIONS = "ADMIN_UPDATE_USER_PERMISSIONS";
export const ADMIN_UPDATE_USER_PERMISSIONS_SUCCEED =
  "ADMIN_UPDATE_USER_PERMISSIONS_SUCCEED";
export const ADMIN_UPDATE_USER_PERMISSIONS_FAILED =
  "ADMIN_UPDATE_USER_PERMISSIONS_FAILED";

export const GET_ROLE_PERMISSIONS = "GET_ROLE_PERMISSIONS";
export const GET_ROLE_PERMISSIONS_SUCCEED = "GET_ROLE_PERMISSIONS_SUCCEED";
export const GET_ROLE_PERMISSIONS_FAILED = "GET_ROLE_PERMISSIONS_FAILED";

export const UPDATE_ROLE_PERMISSIONS_API = "UPDATE_ROLE_PERMISSIONS_API";
export const UPDATE_ROLE_PERMISSIONS_API_SUCCEED =
  "UPDATE_ROLE_PERMISSIONS_API_SUCCEED";
export const UPDATE_ROLE_PERMISSIONS_API_FAILED =
  "UPDATE_ROLE_PERMISSIONS_API_FAILED";

export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCEED = "GET_POSTS_SUCCEED";
export const GET_POSTS_FAILED = "GET_POSTS_FAILED";

export const GET_UNACCEPTED_POST = "GET_UNACCEPTED_POST";
export const GET_UNACCEPTED_POST_SUCCEED = "GET_UNACCEPTED_POST_SUCCEED";
export const GET_UNACCEPTED_POST_FAILED = "GET_UNACCEPTED_POST_FAILED";

export const DELETE_POST_API = "DELETE_POST_API";
export const DELETE_POST_API_SUCCEED = "DELETE_POST_API_SUCCEED";
export const DELETE_POST_API_FAILED = "DELETE_POST_API_FAILED";

export const APPROVE_POST_API = "APPROVE_POST_API";
export const APPROVE_POST_API_SUCCEED = "APPROVE_POST_API_SUCCEED";
export const APPROVE_POST_API_FAILED = "APPROVE_POST_API_FAILED";

export const APPROVE_MULTI_POSTS_API = "APPROVE_MULTI_POSTS_API";
export const APPROVE_MULTI_POSTS_API_SUCCEED =
  "APPROVE_MULTI_POSTS_API_SUCCEED";
export const APPROVE_MULTI_POSTS_API_FAILED = "APPROVE_MULTI_POSTS_API_FAILED";

export const COMPLETE_POST_API = "COMPLETE_POST_API";
export const COMPLETE_POST_API_SUCCEED = "COMPLETE_POST_API_SUCCEED";
export const COMPLETE_POST_API_FAILED = "COMPLETE_POST_API_FAILED";

export const SET_SHOW_SIDEBAR = "SET_SHOW_SIDEBAR";

export const SET_INFO = "SET_INFO";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCEED = "RESET_PASSWORD_SUCCEED";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const CONFIRM_CODE = "CONFIRM_CODE";
export const CONFIRM_CODE_SUCCEED = "CONFIRM_CODE_SUCCEED";
export const CONFIRM_CODE_FAILED = "CONFIRM_CODE_FAILED";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCEED = "CHANGE_PASSWORD_SUCCEED";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

export const APPLY_API = "APPLY_API";
export const APPLY_API_SUCCEED = "APPLY_API_SUCCEED";
export const APPLY_API_FAILED = "APPLY_API_FAILED";

export const GET_POSTS_COMP = "GET_POSTS_COMP";
export const GET_POSTS_COMP_SUCCEED = "GET_POSTS_COMP_SUCCEED";
export const GET_POSTS_COMP_FAILED = "GET_POSTS_COMP_FAILED";

export const GET_APPLIER_API = "GET_APPLIER_API";
export const GET_APPLIER_API_SUCCEED = "GET_APPLIER_API_SUCCEED";
export const GET_APPLIER_API_FAILED = "GET_APPLIER_API_FAILED";

export const ADD_POST_API = "ADD_POST_API";
export const ADD_POST_API_SUCCEED = "ADD_POST_API_SUCCEED";
export const ADD_POST_API_FAILED = "ADD_POST_API_FAILED";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCEED = "GET_PROFILE_SUCCEED";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const GET_CV = "GET_CV";
export const GET_CV_SUCCEED = "GET_CV_SUCCEED";
export const GET_CV_FAILED = "GET_CV_FAILED";

export const GET_ITERCV = "GET_ITERCV";
export const GET_ITERCV_SUCCEED = "GET_ITERCV_SUCCEED";
export const GET_ITERCV_FAILED = "GET_ITERCV_FAILED";

export const CREATE_CV = "CREATE_CV";
export const CREATE_CV_SUCCEED = "CREATE_CV_SUCCEED";
export const CREATE_CV_FAILED = "CREATE_CV_FAILED";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCEED = "UPDATE_PROFILE_SUCCEED";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const GET_SIGNATURE = "GET_SIGNATURE";
export const GET_SIGNATURE_SUCCEED = "GET_SIGNATURE_SUCCEED";
export const GET_SIGNATURE_FAILED = "GET_SIGNATURE_FAILED";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCEED = "UPLOAD_IMAGE_SUCCEED";
export const UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED";

export const UPDATE_CV = "UPDATE_CV";
export const UPDATE_CV_SUCCEED = "UPDATE_CV_SUCCEED";
export const UPDATE_CV_FAILED = "UPDATE_CV_FAILED";

export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCEED = "UPDATE_POST_SUCCEED";
export const UPDATE_POST_FAILED = "UPDATE_POST_FAILED";

export const RECEIVE_EMAIL = "RECEIVE_EMAIL";
export const RECEIVE_EMAIL_SUCCEED = "RECEIVE_EMAIL_SUCCEED";
export const RECEIVE_EMAIL_FAILED = "RECEIVE_EMAIL_FAILED";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCEED = "UPDATE_PASSWORD_SUCCEED";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";

export const CREATE_FEEDBACK = "CREATE_FEEDBACK";
export const CREATE_FEEDBACK_SUCCEED = "CREATE_FEEDBACK_SUCCEED";
export const CREATE_FEEDBACK_FAILED = "CREATE_FEEDBACK_FAILED";

export const DELETE_FEEDBACK = "DELETE_FEEDBACK";
export const DELETE_FEEDBACK_SUCCEED = "DELETE_FEEDBACK_SUCCEED";
export const DELETE_FEEDBACK_FAILED = "DELETE_FEEDBACK_FAILED";

export const GET_FEEDBACK = "GET_FEEDBACK";
export const GET_FEEDBACK_SUCCEED = "GET_FEEDBACK_SUCCEED";
export const GET_FEEDBACK_FAILED = "GET_FEEDBACK_FAILED";

export const GET_LIST_COMPANY = "GET_LIST_COMPANY";
export const GET_LIST_COMPANY_SUCCEED = "GET_LIST_COMPANY_SUCCEED";
export const GET_LIST_COMPANY_FAILED = "GET_LIST_COMPANY_FAILED";

export const GET_POST_LIST = "GET_POST_LIST";
export const GET_POST_LIST_SUCCEED = "GET_POST_LIST_SUCCEED";
export const GET_POST_LIST_FAILED = "GET_POST_LIST_FAILED";

export const GET_POST_DETAIL = "GET_POST_DETAIL";
export const GET_POST_DETAIL_SUCCEED = "GET_POST_DETAIL_SUCCEED";
export const GET_POST_DETAIL_FAILED = "GET_POST_DETAIL_FAILED";

export const ANALYZE_POST = "ANALYZE_POST";
export const ANALYZE_POST_SUCCEED = "ANALYZE_POST_SUCCEED";
export const ANALYZE_POST_FAILED = "ANALYZE_POST_FAILED";

export const ANALYZE_SKILL = "ANALYZE_SKILL";
export const ANALYZE_SKILL_SUCCEED = "ANALYZE_SKILL_SUCCEED";
export const ANALYZE_SKILL_FAILED = "ANALYZE_SKILL_FAILED";

export const ANALYZE_USER = "ANALYZE_USER";
export const ANALYZE_USER_SUCCEED = "ANALYZE_USER_SUCCEED";
export const ANALYZE_USER_FAILED = "ANALYZE_USER_FAILED";

export const SET_POST = "SET_POST";

export const SET_POST_ADMIN = "SET_POST_ADMIN";

